services:
  mysql-source:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: source_db
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-prootpass']
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-target:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: target_db
    ports:
      - '3308:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-prootpass']
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-source:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: source_db
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-target:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: target_db
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-source:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')", '-u', 'admin', '-p', 'rootpass']
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-target:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - '27018:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')", '-u', 'admin', '-p', 'rootpass']
      interval: 5s
      timeout: 5s
      retries: 10
